packages:
  - contracts
  - core
  - compiler
  - gateway
  - market
  - speech
  - frontend/apps/*
  - frontend/packages/*
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.15'
  - '@expo/config-plugins@57.0.8'
  - '@expo/metro-runtime@57.0.10'
  - '@expo/prebuild-config@57.0.12'
  - '@expo/router-server@57.0.6'
  - '@expo/ui@57.0.11'
  - babel-preset-expo@57.0.7
  - expo-asset@57.0.11
  - expo-constants@57.0.11
  - expo-file-system@57.0.3
  - expo-modules-autolinking@57.0.10
  - expo-modules-core@57.0.11
  - expo-router@57.0.13
  - expo-server@57.0.3
  - expo@57.0.13
  - expo-linking@57.0.6
